---
- name: "Install common packages"
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ common_packages }}"

- name: "Install python common modules"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ common_python_modules }}"
